from __future__ import annotations

from dataclasses import dataclass


_FOPEN_SINK = "fopen("


@dataclass(frozen=True, slots=True)
class VulnClassSpec:
    vuln_class: str
    owasp_id: str
    description: str
    runtime_validatable: bool
    sink_patterns: tuple[str, ...]
    intercepts: tuple[str, ...]


VULN_CLASS_SPECS: tuple[VulnClassSpec, ...] = (
    VulnClassSpec(
        vuln_class="sql_injection_boundary",
        owasp_id="A03",
        description="SQL boundary influence",
        runtime_validatable=True,
        sink_patterns=(
            "mysqli_query",
            "mysqli_real_query",
            "mysqli::query",
            "mysqli_multi_query",
            "PDO->query",
            "PDO::query",
            "PDO->prepare",
            "PDO->exec",
            "PDO::exec",
            "pg_query",
        ),
        intercepts=(
            "mysqli_query",
            "mysqli_real_query",
            "mysqli::query",
            "mysqli_multi_query",
            "PDO::query",
            "PDO::prepare",
            "PDO::exec",
            "pg_query",
        ),
    ),
    VulnClassSpec(
        vuln_class="command_injection_boundary",
        owasp_id="A03",
        description="OS command boundary influence",
        runtime_validatable=True,
        sink_patterns=("exec(", "shell_exec(", "system(", "passthru(", "popen(", "proc_open(", "pcntl_exec(", "`"),
        intercepts=("exec", "shell_exec", "system", "passthru", "popen", "proc_open", "pcntl_exec"),
    ),
    VulnClassSpec(
        vuln_class="code_injection_boundary",
        owasp_id="A03",
        description="Dynamic code execution boundary influence",
        runtime_validatable=True,
        sink_patterns=("eval(", "assert(", "preg_replace(", "create_function("),
        intercepts=("eval", "assert", "preg_replace", "create_function"),
    ),
    VulnClassSpec(
        vuln_class="ldap_injection_boundary",
        owasp_id="A03",
        description="LDAP query boundary influence",
        runtime_validatable=True,
        sink_patterns=("ldap_search(", "ldap_list(", "ldap_read(", "ldap_add(", "ldap_modify("),
        intercepts=("ldap_search", "ldap_list", "ldap_read", "ldap_add", "ldap_modify"),
    ),
    VulnClassSpec(
        vuln_class="xpath_injection_boundary",
        owasp_id="A03",
        description="XPath query boundary influence",
        runtime_validatable=True,
        sink_patterns=("DOMXPath::query", "DOMXPath::evaluate", "SimpleXMLElement::xpath"),
        intercepts=("DOMXPath::query", "DOMXPath::evaluate", "SimpleXMLElement::xpath"),
    ),
    VulnClassSpec(
        vuln_class="file_boundary_influence",
        owasp_id="A01",
        description="File boundary influence",
        runtime_validatable=True,
        sink_patterns=(
            "file_put_contents",
            "file_get_contents",
            _FOPEN_SINK,
            "include(",
            "include_once(",
            "require(",
            "require_once(",
            "readfile(",
            "file(",
            "show_source(",
            "highlight_file(",
        ),
        intercepts=(
            "file_put_contents",
            "file_get_contents",
            "fopen",
            "include",
            "include_once",
            "require",
            "require_once",
            "readfile",
            "file",
            "show_source",
            "highlight_file",
        ),
    ),
    VulnClassSpec(
        vuln_class="file_upload_influence",
        owasp_id="A01",
        description="File upload boundary influence",
        runtime_validatable=True,
        sink_patterns=("move_uploaded_file(", "finfo_file(", "mime_content_type("),
        intercepts=("move_uploaded_file", "finfo_file", "mime_content_type"),
    ),
    VulnClassSpec(
        vuln_class="xss_output_boundary",
        owasp_id="A03",
        description="Unescaped output boundary influence",
        runtime_validatable=True,
        sink_patterns=("echo ", "print ", "printf(", "vprintf(", "die(", "exit("),
        intercepts=(),
    ),
    VulnClassSpec(
        vuln_class="debug_output_leak",
        owasp_id="A09",
        description="Debug output leak surface",
        runtime_validatable=True,
        sink_patterns=("print_r(", "var_dump(", "var_export(", "phpinfo("),
        intercepts=(),
    ),
    VulnClassSpec(
        vuln_class="outbound_request_influence",
        owasp_id="A10",
        description="Outbound request influence",
        runtime_validatable=True,
        sink_patterns=("curl_exec", "curl_setopt", "CURLOPT_URL", "file_get_contents(", _FOPEN_SINK, "fsockopen(", "pfsockopen("),
        intercepts=("curl_exec", "curl_setopt", "file_get_contents", "fopen", "fsockopen", "pfsockopen"),
    ),
    VulnClassSpec(
        vuln_class="xxe_influence",
        owasp_id="A05",
        description="XML external entity processing boundary",
        runtime_validatable=True,
        sink_patterns=(
            "DOMDocument::load(",
            "DOMDocument::loadXML(",
            "simplexml_load_file(",
            "simplexml_load_string(",
            "xml_parse(",
        ),
        intercepts=(
            "DOMDocument::load",
            "DOMDocument::loadXML",
            "simplexml_load_file",
            "simplexml_load_string",
            "xml_parse",
        ),
    ),
    VulnClassSpec(
        vuln_class="deserialization_influence",
        owasp_id="A08",
        description="Deserialization reachability",
        runtime_validatable=True,
        sink_patterns=("unserialize(", "json_decode("),
        intercepts=("unserialize", "json_decode"),
    ),
    VulnClassSpec(
        vuln_class="php_object_gadget_surface",
        owasp_id="A08",
        description="Magic method gadget surface",
        runtime_validatable=True,
        sink_patterns=("__wakeup(", "__destruct(", "__toString(", "__call(", "__get(", "__set("),
        intercepts=("__wakeup", "__destruct", "__toString", "__call", "__get", "__set"),
    ),
    VulnClassSpec(
        vuln_class="header_injection_boundary",
        owasp_id="A03",
        description="HTTP/SMTP header manipulation boundary",
        runtime_validatable=True,
        sink_patterns=("header(", "mail(", "mb_send_mail("),
        intercepts=("header", "mail", "mb_send_mail"),
    ),
    VulnClassSpec(
        vuln_class="regex_dos_boundary",
        owasp_id="A10",
        description="Regex resource exhaustion surface",
        runtime_validatable=True,
        sink_patterns=("preg_match(", "preg_match_all(", "preg_replace(", "max_input_vars"),
        intercepts=("preg_match", "preg_match_all", "preg_replace"),
    ),
    VulnClassSpec(
        vuln_class="xml_dos_boundary",
        owasp_id="A10",
        description="XML parser resource exhaustion surface",
        runtime_validatable=True,
        sink_patterns=("DOMDocument::loadXML(", "simplexml_load_string(", "xml_parse("),
        intercepts=("DOMDocument::loadXML", "simplexml_load_string", "xml_parse"),
    ),
    VulnClassSpec(
        vuln_class="broken_access_control",
        owasp_id="A01",
        description="Access control invariant checks",
        runtime_validatable=True,
        sink_patterns=("$_GET", "$_POST", "is_admin", "authorize"),
        intercepts=(),
    ),
    VulnClassSpec(
        vuln_class="csrf_invariant_missing",
        owasp_id="A01",
        description="Potential missing CSRF verification",
        runtime_validatable=True,
        sink_patterns=("$_SESSION", "csrf", "csrf_token", "hash_equals("),
        intercepts=(),
    ),
    VulnClassSpec(
        vuln_class="idor_invariant_missing",
        owasp_id="A01",
        description="Potential direct object reference without authz invariant",
        runtime_validatable=True,
        sink_patterns=("$_GET['id']", "$_POST['id']", "findById(", "getById(", "loadById("),
        intercepts=(),
    ),
    VulnClassSpec(
        vuln_class="session_fixation_invariant",
        owasp_id="A07",
        description="Session fixation hardening invariants",
        runtime_validatable=True,
        sink_patterns=("session_start(", "session_regenerate_id("),
        intercepts=(),
    ),
    VulnClassSpec(
        vuln_class="crypto_failures",
        owasp_id="A02",
        description="Weak crypto or transport",
        runtime_validatable=False,
        sink_patterns=("md5(", "sha1(", "openssl_encrypt(", "crypt(", "rand(", "mt_rand(", "uniqid(", "shuffle(", "array_rand("),
        intercepts=(),
    ),
    VulnClassSpec(
        vuln_class="security_misconfiguration",
        owasp_id="A05",
        description="Misconfiguration indicators",
        runtime_validatable=True,
        sink_patterns=("display_errors", "ini_set(", "error_reporting("),
        intercepts=("ini_set", "error_reporting"),
    ),
    VulnClassSpec(
        vuln_class="insecure_design",
        owasp_id="A04",
        description="Insecure design indicators",
        runtime_validatable=False,
        sink_patterns=("allow_all_access", "bypass_auth", "skip_authorization", "trust_client_role"),
        intercepts=(),
    ),
    VulnClassSpec(
        vuln_class="vulnerable_components",
        owasp_id="A06",
        description="Dependency and supply-chain risk indicators",
        runtime_validatable=False,
        sink_patterns=("composer.json", "composer.lock"),
        intercepts=(),
    ),
    VulnClassSpec(
        vuln_class="auth_and_session_failures",
        owasp_id="A07",
        description="Authentication/session anti-patterns",
        runtime_validatable=True,
        sink_patterns=("session_start", "password_verify", "setcookie("),
        intercepts=(),
    ),
    VulnClassSpec(
        vuln_class="software_data_integrity",
        owasp_id="A08",
        description="Integrity and unsafe update channels",
        runtime_validatable=False,
        sink_patterns=("eval(", "assert(", "include(", "require("),
        intercepts=(),
    ),
    VulnClassSpec(
        vuln_class="logging_monitoring_failures",
        owasp_id="A09",
        description="Missing audit and error logging",
        runtime_validatable=False,
        sink_patterns=("error_log(", "logger", "audit"),
        intercepts=(),
    ),
    VulnClassSpec(
        vuln_class="ssrf",
        owasp_id="A10",
        description="Server-side request forgery",
        runtime_validatable=True,
        sink_patterns=("curl_exec", "curl_setopt", "CURLOPT_URL", "file_get_contents(", _FOPEN_SINK, "fsockopen(", "pfsockopen("),
        intercepts=("curl_exec", "curl_setopt", "file_get_contents", "fopen", "fsockopen", "pfsockopen"),
    ),
    VulnClassSpec(
        vuln_class="information_disclosure",
        owasp_id="A09",
        description="Sensitive information disclosure indicators",
        runtime_validatable=True,
        sink_patterns=("phpinfo(", "display_errors", "print_r(", "var_dump(", "var_export("),
        intercepts=(),
    ),
)


def intercepts_for_class(vuln_class: str) -> list[str]:
    for spec in VULN_CLASS_SPECS:
        if spec.vuln_class == vuln_class:
            return list(spec.intercepts)
    return []
